- hosts: instancias-aws
  tasks:
  - name: criando o arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Pagina html provisionada e configurada com Terraform e Ansible - V2</h1>
  - name: criando o servidor http
    shell: "nohup busybox httpd -f -p 8080 &"
  - name: instalando o python 3, virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Instalando dependencias Django e Django rest com pip
    pip:
      virtualenv: /home/ubuntu/novapasta/venv
      name:
        - django
        - djangorestframework
  - name: Iniciando o projeto django
    shell: '. /home/ubuntu/novapasta/venv/bin/activate; django-admin startproject setup /home/ubuntu/novapasta/'
  - name: Alterando o hosts no arquivo settings
    lineinfile:
      path: /home/ubuntu/novapasta/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS["*"]'
      backrefs: yes
