- hosts: instancias-aws
  tasks:
  - name: criando o arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Pagina html provisionada e configurada com Terraform e Ansible - V2</h1>
  - name: criando o servidor http
    shell: "nohup busybox httpd -f -p 8080 &"
